FROM gcc:4.9 AS binaries

WORKDIR /home/server

RUN apt update -y

RUN apt-get install libcurl4-gnutls-dev -y

RUN apt-get install libjansson-dev -y

RUN apt-get install libb64-dev -y

COPY ./ ./

RUN gcc server.c -o server.o -ljansson -lcurl -lb64 -std=gnu11

FROM ubuntu

WORKDIR /home/server

RUN apt update -y

RUN apt-get install libcurl4-gnutls-dev -y

RUN apt-get install libjansson-dev -y

RUN apt-get install libb64-dev -y

RUN apt install dnsutils vim -y


COPY --from=binaries /home/server/ ./


#ENTRYPOINT ["./server.o"]
ENTRYPOINT ["tail", "-f", "/proc/1/fd/1"]
